### ISSUE TITLE
Add RMRK off chain voting spaces to asset detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#1006]
Add both the 2 spaces.

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1320%3A7755

preview
![image](https://user-images.githubusercontent.com/59445675/149738804-ac910a50-1da3-4265-b108-2570e6c40b32.png)
