### ISSUE TITLE
Update asset #45 info (TBD)

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/statescan#1036]
refer to
https://statemine.statescan.io/asset/45_1243780

---

Logo
[logo-monkeydoodle.zip](https://github.com/opensquare-network/statescan/files/8258736/logo-monkeydoodle.zip)

Symbol
CRIB

Name
Crib

About
Crib Coin

Links
website (link icon)
https://www.monkeydoodle.io/

**Comment by wliyongfeng** [comment]
I can not get confirmation from the team, so I will close this issue.
