### ISSUE TITLE
Incorrect locked balance

### ISSUE THREAD

**Issue by gilescope** [opensquare-network/statescan#1038]
Here it says the balance is locked when I believe it is not:

https://westmint.statescan.io/account/5DvoL2BNoSm7wRt2tfZ6WW5QFrxm68GLv5SCrPQ4JBLjbvpL?tab=extrinsics

but I don't believe it is. The collator deposit of 10 WND gets unlocked when the collator gets kicked (This happens on a new session) here:

https://westmint.statescan.io/event/1722600-1

I suspect this is a bit of an edge case that statescan is possibly not expecting?

Thank you btw for the https://westmint.statescan.io/events?page=1&module=collatorSelection page - this was most helpful for diagnostics.

**Comment by wliyongfeng** [comment]
Hey @gilescope , thanks a lot for reporting this issue. Sure you're right, I checked the address balance and there is no lock.

![VKAcH8ACn2](https://user-images.githubusercontent.com/2264908/158596784-e013ba4d-1b62-4be5-a882-b0bf1917f817.png)

Actually we haven't handle the cases with collators, but will add the logics ASAP. Thanks again.

**Comment by wliyongfeng** [comment]
We fixed westmint with the latest version, but it seems this account is added as curator again. So there is still 10 WND reserved.
