### ISSUE TITLE
Images don't show up on Statemine

### ISSUE THREAD

**Issue by tash-2s** [opensquare-network/statescan#1064]
I minted NFTs on Statemine, but Statescan doesn't display these images on the instance pages.
https://statemine.statescan.io/nft/classes/3/instances/0

The same metadata has been used on Westmint, and they're displayed as expected.
https://westmint.statescan.io/nft/classes/6/instances/0

On the class page, small thumbnail images of the instances are shown without issues.
https://statemine.statescan.io/nft/classes/3

Could you check this? @wliyongfeng @hyifeng

**Comment by hyifeng** [comment]
@tash-2s Images are now display correctly, please check again.

**Comment by tash-2s** [comment]
Thanks again! Great work.
