### ISSUE TITLE
Fix display error

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/statescan#1082]
[Link](https://statemine.statescan.io/nft/classes/61866?tab=timeline)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/179475234-46fa43de-8a31-422e-ad3f-21ca9a33f641.png">

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/182318155-5b559f82-cbd6-4afc-bb9c-861887b21051.png)
