### ISSUE TITLE
Search result list UI issue

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#283]
<img width="734" alt="Screen Shot 2021-07-14 at 6 19 47 PM" src="https://user-images.githubusercontent.com/2264908/125606420-1ba8cc1f-2044-49c4-9458-3e932ce9bbc2.png">

`CHV TKN` is too long, please talk to @Popoulosss to find a solution for UI.

**Comment by Popoulosss** [comment]
![image](https://user-images.githubusercontent.com/59445675/125607658-a4e0c379-2ab5-4f03-8ce2-36ad265cedfe.png)

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=395%3A2074
