### ISSUE TITLE
Change the font size of the tooltip

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/statescan#453]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=723%3A148

preview
![image](https://user-images.githubusercontent.com/59445675/128314285-d68c9be0-7efe-4d0b-b0b1-643152613217.png)

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/128830715-068de588-5a8c-405b-8b61-e3ce95f2bfdc.png)
