### ISSUE TITLE
UI improve

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/statescan#465]
![image](https://user-images.githubusercontent.com/12393771/128825202-6d662413-710e-43e5-bc62-29baca51fc75.png)

**Comment by Popoulosss** [comment]
![image](https://user-images.githubusercontent.com/59445675/128990274-c8a908fd-f603-417c-a918-78e082ac26c7.png)

**Comment by Popoulosss** [comment]
![image](https://user-images.githubusercontent.com/59445675/128990502-095048c6-8531-4ab9-8c41-d40403a5e74c.png)

**Comment by Popoulosss** [comment]
![image](https://user-images.githubusercontent.com/59445675/128990821-3f8a5288-c2f2-4fc1-a1a2-74aa716bc96e.png)
