### ISSUE TITLE
Refactor footer

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#488]
- Remove donation
- Add following links
  - github repo
  - twitter
  - email
  - element room
- Add 'Funded by Kusama Treasury'

![Lark20210812-171604](https://user-images.githubusercontent.com/2264908/129172071-0d460eb5-d17f-4c6e-b853-7a8c1c60b4a7.png)

**Comment by Popoulosss** [comment]
figma link
web
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=66%3A0
mobile
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1299%3A7384

**Comment by wliyongfeng** [comment]
element link: https://app.element.io/#/room/#opensquare:matrix.org
github: https://github.com/opensquare-network/
email: hi@opensquare.network
twitter: https://twitter.com/OpensquareN
