### ISSUE TITLE
Add logo and profile info for RMRK token

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#539]
- Web: https://rmrk.app
- Marketplace: https://singular.rmrk.app
- RMRK 2.0 Marketplace: https://kanaria.rmrk.app
- Twitter: @rmrkapp
- Status Twitter: @rmrkstatus
- Telegram: t.me/kanaria_official (Kanaria project) and t.me/rmrkapp (RMRK in general)
- Blog: https://app.subsocial.network/@rmrkapp

@Popoulosss I think we need icons for these social websites.

**Comment by wliyongfeng** [comment]
@Popoulosss We have to choose one for RMRK avatar.

Logo candidates:

1st:

![7150b1bd-40d4-4b5e-9cb6-612d929f5b39](https://user-images.githubusercontent.com/2264908/133882309-abb153b4-4cc9-4962-803d-e32a33440f68.png)

2nd:
![1c62f19c-96bf-43aa-943e-c0f42403cf1d](https://user-images.githubusercontent.com/2264908/133882356-bd0016ed-df46-4a8a-aecc-1c28fe6c1ff3.png)

3rd:
![37917932-3120-4f5f-a650-d50e8ac0fbc8](https://user-images.githubusercontent.com/2264908/133882341-2e9d6bd6-5ec1-44cb-813c-7fa0a934121c.png)

4th:
![df497b08-bacf-4b91-bcd9-492dc214d504](https://user-images.githubusercontent.com/2264908/133882375-c9e939c7-9e24-4801-87e5-f220f0f993e8.png)

**Comment by Popoulosss** [comment]
file
[icons.zip](https://github.com/opensquare-network/statescan/files/7189600/icons.zip)

preview
![image](https://user-images.githubusercontent.com/59445675/133883070-22a4f680-23ee-4792-90a3-d3764ecf0308.png)

**Comment by wliyongfeng** [comment]
@Popoulosss We also need icons for twitter, telegram, subsocial.

**Comment by Popoulosss** [comment]
- [ ] Add link icons(default/twitter/telegram/subsocial...) to asset
- [ ] Show detail while hovering icon

file
[icons.zip](https://github.com/opensquare-network/statescan/files/7193722/icons.zip)

preview
![image](https://user-images.githubusercontent.com/59445675/133960332-ed98380f-3ac7-4a37-a793-358bff39d829.png)
![image](https://user-images.githubusercontent.com/59445675/133960384-a03f2fbc-c3bd-44e5-a5d9-1af0293c6427.png)

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1320%3A7746

@qiyisi

**Comment by Popoulosss** [comment]
Web: https://rmrk.app
Twitter: @rmrkapp: https://twitter.com/RmrkApp
Twitter: @rmrkstatus: https://twitter.com/rmrkstatus
Telegram: Kanaria project: https://t.me/kanaria_official
Telegram: RMRK in general: https://t.me/rmrkapp
Subsocial: https://app.subsocial.network/@rmrkapp
