### ISSUE TITLE
Module and call should be highlighted on extrinsic detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#567]
Reason: these 2 fields are more important compared to others.
Refer to extrinsic detail page on subscan.

![飞书20210925-130828](https://user-images.githubusercontent.com/2264908/134759119-56b92f15-490d-4068-93b6-1ff6f81f3a98.png)

@Popoulosss

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=2066%3A24363

preview
![image](https://user-images.githubusercontent.com/59445675/134759916-06a64476-54cc-4e04-b447-f252c988e234.png)

**Comment by wliyongfeng** [comment]
@qiyisi Plz implement it.
