### ISSUE TITLE
Show also block number on asset timeline items

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#575]
![飞书20210926-230152](https://user-images.githubusercontent.com/2264908/134813220-6eeae5d7-19bc-4ce5-992e-4c5011eff7c0.png)

@Popoulosss Plz give design
@YoshiyukiSakura Plz implement it

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1320%3A8732

preview
![image](https://user-images.githubusercontent.com/59445675/134814330-18eaf38b-640b-44bf-9793-0b57321b3a43.png)
