### ISSUE TITLE
Show  asset Destroyed or Frozen status

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#576]
![飞书20210927-000153](https://user-images.githubusercontent.com/2264908/134815293-e7c4adf7-846d-4375-9dd9-a8d5af146a09.png)

There is one 99 asset which is destroyed.

- [x] We add a destroyed mark|icon for the destroyed one
- [x] On Asset detail page, add a status field **highlighted** show the asset status(Active, Frozen, Destroyed).

@Popoulosss Plz give the design.
@YoshiyukiSakura Plz implement it.

**Comment by Popoulosss** [comment]
- [ ] Add a destroyed icon for the destroyed asset
- [ ] Show tooltip while hovering on the asset icon

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=37%3A18874

preview
![image](https://user-images.githubusercontent.com/59445675/134842424-065bb35a-5406-4e45-aa14-b3ab967acbea.png)

----

- [ ] On Asset detail page, add a status field highlighted show the asset status(Active, Frozen, Destroyed)

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=609%3A12

preview
web
![image](https://user-images.githubusercontent.com/59445675/134842488-f106717e-744d-4e96-a15d-5bf9ee2aefcb.png)

mobile
![image](https://user-images.githubusercontent.com/59445675/134842517-65103a00-3248-4655-a9d0-09db583db665.png)
