### ISSUE TITLE
Add more links for RMRK

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#590]
discord: https://discord.com/invite/SpNEQSSwWv
youtube: https://www.youtube.com/channel/UCZ9dCwNm2aErxsYxDdm-AtQ

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1320%3A7762

preview
![image](https://user-images.githubusercontent.com/59445675/136495326-0cdc1a86-1350-4cbc-8b2f-c11710389667.png)

file
[icons.zip](https://github.com/opensquare-network/statescan/files/7308360/icons.zip)
