### ISSUE TITLE
As a owner of asset, I want to upload some links and description for my asset

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#599]
- [ ] Maybe create a google form to collect images or descriptions
- [x] Create some components on asset page for asset owner to submit

**Comment by Popoulosss** [comment]
preview
![image](https://user-images.githubusercontent.com/59445675/138387963-0841a356-f7cb-4886-be02-96123b07a14a.png)
![image](https://user-images.githubusercontent.com/59445675/138387977-db629ee5-45ea-461c-aaa5-bcf731aa5679.png)

**Comment by Popoulosss** [comment]
- [ ] Change size to 52px

preview
![image](https://user-images.githubusercontent.com/59445675/138392349-d0067f1d-50d9-4830-bd43-02062dcf6d0f.png)
