### ISSUE TITLE
Asset total supply view

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#697]
![MyA0CmbmJv](https://user-images.githubusercontent.com/2264908/140645365-fcadf426-14b2-4a57-9c97-7bd41b8cffcd.png)

**Comment by Popoulosss** [comment]
- [ ] If the number is large than Quadrillion(groups of (3) zeros >=5)(10,000,000,000,000,000), show as abbreviation(10Q)(ignore small values)
- [ ] when hovering on the number, tooltip shows full value

refer to
https://www.thoughtco.com/zeros-in-million-billion-trillion-2312346

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=111%3A431

preview
![image](https://user-images.githubusercontent.com/59445675/140687530-2c5aab74-d7f3-46ea-a0bb-d767ce9c5455.png)

**Comment by hyifeng** [comment]
- [ ] Tooltip format
![image](https://user-images.githubusercontent.com/6297057/141718599-4d6fb459-6ba1-4d6b-a105-d3fbb11a2d5f.png)
