### ISSUE TITLE
Add NFT tab to Account detail page

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan#713]
![image](https://user-images.githubusercontent.com/6297057/140845282-798fe099-7210-4c96-8de7-d80b1ad8d3e0.png)

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=2115%3A8150

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/141219477-cd6dc573-0420-4556-bcf7-03f90d95cef5.png)
## we have got a different column, please double check
