### ISSUE TITLE
Add NFT Transfer tab to Account detail page

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan#714]

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=3632%3A14919

preview
![image](https://user-images.githubusercontent.com/59445675/141053446-eac2b5c7-995f-46bb-aa1c-9ab05e4f20ed.png)

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/141219239-065c98c2-dec2-4ea6-9ba2-e0f0dc01930c.png)
## please change columns order, to  time/age , NFT , Name ... and also check for column width
