### ISSUE TITLE
"Approved" balances still displaying after cancelApproval

### ISSUE THREAD

**Issue by adamsteeber** [opensquare-network/statescan#755]
I set some approvals that were intended to be balance transfers in the following tx:

https://statemine.statescan.io/extrinsic/0x31ec3d7793ad2cd66e48ac79e6a5f38c5fd49965b3cfb1c9d23bd49736470633

So I cancelled these approvals in the following tx:

https://statemine.statescan.io/extrinsic/0xc729a44ceeeac80cd078616b8d8033bd7d77008037030dbe6f869890c5db9a34

Yet, if you look at the account it still displayed an "Approved" balance for the token.

**Comment by wliyongfeng** [comment]
@adamsteeber Thanks, confirmed. There's a bug in the approval update process, fixing.
