### ISSUE TITLE
Review and complete the NFT timeline

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan#756]
- [x] Add icons: Redeposited, ApprovedTransfer, ApprovalCancelled

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=3259%3A14374

preview
![image](https://user-images.githubusercontent.com/59445675/141715940-dca375e7-aa00-4e21-92d1-032d8a11bfd9.png)
