### ISSUE TITLE
Add NFT records to extrinsic detail

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/statescan#773]
- [x] Implemented.
- [x] Click on the thumbnails to show details.

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=3765%3A15107

preview
![image](https://user-images.githubusercontent.com/59445675/141720738-dbdb9acf-c5c2-4f8b-9cc9-5b87b197e467.png)

**Comment by YoshiyukiSakura** [comment]
gj
