### ISSUE TITLE
Add NFT to the search results and optimize display

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/statescan#821]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=3983%3A18989

- [x] Add button to textfield for clearing 

preview
![image](https://user-images.githubusercontent.com/59445675/142557286-89208e16-e4c0-4e22-8016-e54f5c701aa7.png)

- [x] Add NFT to the search results

preview
![image](https://user-images.githubusercontent.com/59445675/142557355-cb0a7c17-d197-4c05-9520-46f5a498ed82.png)

- [x] Optimize layout of search result

preview
![image](https://user-images.githubusercontent.com/59445675/142557481-15c499e5-f583-452c-9693-a4abdbf6e0d9.png)

**Comment by hyifeng** [comment]
- [ ] Fix unrecognized item in search result
![image](https://user-images.githubusercontent.com/6297057/142621714-ff5342f9-2748-4602-b678-b004f3b6a2f5.png)

**Comment by hyifeng** [comment]
- [ ] Click on the search result (NFT instance) does not open the corresponding page
![image](https://user-images.githubusercontent.com/6297057/142797667-f14703eb-3fad-4b22-bc70-a4a171137414.png)
