### ISSUE TITLE
system#setCode, the code arguments should be customized 

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan#834]
- [ ] When the code is not large, show all the hex
- [ ] When the code is large, show a short info like 0x123...456, then followed by a download button which user can click to download all the hex.
- [ ] For JSON, we don't have to show the download button. Only show 0x123...456.

**Comment by YoshiyukiSakura** [comment]
no such data currently  
might wait until its scaned

**Comment by wliyongfeng** [comment]
We should improve the extrinsic `parachainSystem#enactAuthorizedUpgrade`, check following extrinsics:

https://statemine.statescan.io/extrinsics?page=1&module=parachainSystem&method=enactAuthorizedUpgrade
