### ISSUE TITLE
Track price of fungible assets

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#843]
Currently only $RMRK

**Comment by Popoulosss** [comment]
display asset price/usd price
- [ ] asset table
- [ ] account asset table (usd price)
- [ ] asset detail

asset table
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=2854%3A13189
![image](https://user-images.githubusercontent.com/59445675/143418515-2da4fb39-7fe7-4e47-9b15-1cc2528fa888.png)
![image](https://user-images.githubusercontent.com/59445675/143418610-5d389352-e184-4c08-8f9e-89d3b98aff81.png)

account asset table
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=111%3A301
![image](https://user-images.githubusercontent.com/59445675/143418067-eeeecaa3-9405-4e2c-8d62-9ba1e2ea28d8.png)

asset detail
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1320%3A7754
![image](https://user-images.githubusercontent.com/59445675/143374144-5599181f-9e06-4124-8e9c-e89d450a4c63.png)
