### ISSUE TITLE
Implement destroyed assets list

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan#847]
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=4044%3A15552

![image](https://user-images.githubusercontent.com/6297057/143371511-54d4ee6a-4052-42c4-bd75-ecfbd199c272.png)

**Comment by Popoulosss** [comment]
assets list
- Assets ID
- Symbol
- Name
- Destroyed Time
- Owner
- Total Destroyed
