### ISSUE TITLE
Implement destroyed NFT classes list

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan#849]
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=4099%3A16321

![image](https://user-images.githubusercontent.com/6297057/143371710-615a750e-a201-41ef-a221-a780e10f0cbd.png)

**Comment by Popoulosss** [comment]
NFT class list
- Class ID
- NFT
- Name
- Destroyed Time
- Owner
- Instance
