### ISSUE TITLE
Customize 500 internal server error page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#894]
![JoZ3q3BPTo](https://user-images.githubusercontent.com/2264908/145510983-e6d7b88b-558c-4f76-a4e4-a0e1d8e58bb6.png)

Currently we show the default 500 page by next, but we should show one by SubSquare.

**Comment by Popoulosss** [comment]
- [ ] Optimize 404 page, add description and fixed width

figma link
https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=2068%3A22226

preview
![image](https://user-images.githubusercontent.com/59445675/145958898-dad61ca2-046f-47b8-96a0-2dbd37f0c5af.png)

**Comment by Popoulosss** [comment]
- [ ] Add 500, 503, 505 page

figma link
https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=3121%3A27505

preview
![image](https://user-images.githubusercontent.com/59445675/145959027-e76c9174-9384-4ede-afe9-125ec0e5fb17.png)

**Comment by wliyongfeng** [comment]
@qiyisi, plz implement the pages
