### ISSUE TITLE
Add NFT related info to the status bar under search box

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#895]
@Popoulosss I think we may have designed this.

@qiyisi we may implement this after @Popoulosss 's confirmation.

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=2854%3A13122

preview
![image](https://user-images.githubusercontent.com/59445675/145938496-327e0833-7455-46ee-8646-45bf67b360b3.png)

**Comment by wliyongfeng** [comment]
@hyifeng Please implement server side code to feed corresponding NFT data.

**Comment by Popoulosss** [comment]
- [ ] Change font size
- [ ] Margin top t0 24px

preview
![image](https://user-images.githubusercontent.com/59445675/145938630-4e4867e4-8640-4643-9263-159cd3637d63.png)

**Comment by Popoulosss** [comment]
- [ ] Add icons
- [ ] Display the amounts of NFT Class and NFT instance
- [ ] Recognized / All
- [ ] Show tooltip when hover on icon

preview
![image](https://user-images.githubusercontent.com/59445675/145939259-441d6afe-5db0-45c9-8039-6d0051138064.png)

**Comment by Popoulosss** [comment]
Optimize chart
- [ ] Modify title
- [ ] Add x, y axis

preview
![image](https://user-images.githubusercontent.com/59445675/145939821-ea95725b-6ac0-4ce7-b096-1e0de5087b7d.png)

**Comment by Popoulosss** [comment]
- [ ] Mobile version

preview
![image](https://user-images.githubusercontent.com/59445675/145940605-010ffc66-ad06-454b-acd8-a47e182d147f.png)
