### ISSUE TITLE
Optimize teleports list page

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/statescan#899]
- [x] Add direction filter
- [x] Display transactions from Kusama to Statemine by default
- [x] Display tip on the list from from Kusama to Statemine
- [x] Add text and change kusama icon's size
- [x] Optimize the cell width of the table

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1765%3A7331

preview
![image](https://user-images.githubusercontent.com/59445675/145989755-3a8bbc55-3a13-4a69-a420-24d32de27b8c.png)

**Comment by Popoulosss** [comment]
- [ ] Add a column of executed to the table from Statemine to Kusama
- [ ] Change kusama icon's size
- [ ] Optimize the cell width of the table
- [ ] Switch to sender when you click receiver

**Comment by Popoulosss** [comment]
- [ ] Mobile UI

**Comment by Popoulosss** [comment]
- [ ] Optimize display of teleports table in account page
- [ ] Add filter panel

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=4283%3A20989

preview
![image](https://user-images.githubusercontent.com/59445675/146158974-a0e891cf-892b-495a-8955-0be299138549.png)

**Comment by hyifeng** [comment]
- [ ] Some fields are missing in Mobile UI

![image](https://user-images.githubusercontent.com/6297057/146869061-4d959f81-38a6-480d-b120-3710059eba04.png)

![image](https://user-images.githubusercontent.com/6297057/146869146-caf3c757-1731-4b06-8a76-e670595fabaa.png)
