### ISSUE TITLE
Extrinsic/event dropbox has not enough space to show the full name

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#901]
![P9t8RGOSco](https://user-images.githubusercontent.com/2264908/146122906-31ac6763-1f20-4f36-9a39-33e95a3d6c4f.png)

**Comment by Popoulosss** [comment]
Web
- [ ] Dropdown menu Minimum width 160px(Align with the select box)
- [ ] Responsive width depends on the length of the text
- [ ] Ellipsis for overflow text in select box

Mobile
- [ ] Dropdown menu width Align with the select box

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=4275%3A20439

preview
![image](https://user-images.githubusercontent.com/59445675/146155454-fc9c98f5-abc1-456a-bebc-cdff1749c205.png)
