### ISSUE TITLE
Account - NFT transfer - Age/DateTime is incorrect

### ISSUE THREAD

**Issue by CrommVardek** [opensquare-network/statescan#929]
Hello, 

As an example, navigating here : https://statemine.statescan.io/account/JCkD7cRTpfkQmk5v6XvWvR1JPTvrouPXSGmQqtWPcJQKFzx?tab=nft+transfer 

DateTime displayed is today's date at 00:00:00 (so age is current time), however the extrinsic of that transfer is showing the correct DateTime (extrinsic in question : https://statemine.statescan.io/extrinsic/747243-2 )

So I think the Account/NFT-Transfer/Age is bugged.

**Comment by hyifeng** [comment]
@CrommVardek The issue has been resolved, thank you for reporting.
