### ISSUE TITLE
Asset and NFT order should keep same

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#942]
Top should the oldest, bottom should be the newest.
- [x] Sort method:
1. First sort by block number
2. If block number is same, sort by extrinsic index
3. If block number and extrinsic index is same, sort by the event index

- [x] We also maybe give a better design for the sort, maybe an arrow at the end of line. @Popoulosss

**Comment by Popoulosss** [comment]
> We also maybe give a better design for the sort, maybe an arrow at the end of line.

- [ ] Add 'Back to Top'(?)

figma link
https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/statescan?node-id=1320%3A7745

UI refer to
![image](https://user-images.githubusercontent.com/59445675/147333841-608118ea-eb9a-46d8-a527-439916fb5c30.png)


preview
![image](https://user-images.githubusercontent.com/59445675/147333808-e589c3a5-ad9e-4927-a8f4-0b69cc273be9.png)
