### ISSUE TITLE
Incorect Assest details after recreation

### ISSUE THREAD

**Issue by ksmnetwork** [opensquare-network/statescan#960]
The page present wrong details after the "Asset" is recreated with different ID, the original Asset ID is saved as relation to the creator account and it seems is not updating it with the newlly created asset details. 

Originally the Asset was with ID:823 and latter was destroyed and created as ID:49 
https://statemine.statescan.io/asset/49
Un-existing asset: 
https://statemine.statescan.io/asset/823

Account: H1bSKJxoxzxYRCdGQutVqFGeW7xU3AcN6vyEdZBU7Qb1rsZ
Account Link: https://statemine.statescan.io/account/H1bSKJxoxzxYRCdGQutVqFGeW7xU3AcN6vyEdZBU7Qb1rsZ?tab=assets

**Comment by wliyongfeng** [comment]
@ksmnetwork Thanks for your report. There is a bug about destroyed asset in the scan scripts, fixing it.

**Comment by wliyongfeng** [comment]
@ksmnetwork We fixed it and rescan the data, plz check the assets page.

**Comment by ksmnetwork** [comment]
It shows only the destroyed assets, I assume this is correct. But is not showing the acual one that exist:

Link to account overwive: 
https://statemine.statescan.io/account/H1bSKJxoxzxYRCdGQutVqFGeW7xU3AcN6vyEdZBU7Qb1rsZ

Link to exisintg assest:
https://statemine.statescan.io/asset/49

In addition I check the URI's listed on the Asset overview page, they point to the correct address so is only on the account page, same as the first Link:
https://statemine.statescan.io/account/H1bSKJxoxzxYRCdGQutVqFGeW7xU3AcN6vyEdZBU7Qb1rsZ

**Comment by wliyongfeng** [comment]
@ksmnetwork Sorry, not so clear to me. Could you make a screenshot to describe the problem?

**Comment by ksmnetwork** [comment]
The "Asset" that the account is ID:49 and the website page shows ID:832.

Account screenshot
![Screenshot 2022-01-06 at 13-26-41 Kusama Polkadot Asset Explorer](https://user-images.githubusercontent.com/87113727/148383168-dcbb3263-ced9-4fb5-97c2-c35d98142d59.png)
 
Asset screnshot
![Screenshot 2022-01-06 at 13-33-47 Kusama Polkadot Asset Explorer](https://user-images.githubusercontent.com/87113727/148383746-c0aaa352-6acf-4f59-aef5-043f80bddbf8.png)

You can see that Asset ID:49 is shows the same account as Owner, but on the Account screenshot the Asset is not listed at all.

**Comment by wliyongfeng** [comment]
> The "Asset" that the account hold is ID:49 and the website page shows ID:832.

Thanks, showing asset 832 (destroyed assets) is a bug. We have known it and will fix it soon.

For No. 49 asset, under assets tab we only show the hold assets, but not the 'owned' assets. No.49 asset currently has no holders, so no account will have the asset shown.

**Comment by ksmnetwork** [comment]
Ah the "hold assets" only, now is clear. Thank you!
