### ISSUE TITLE
NFT Metadata#data should be converted to string from hex

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan#992]
![IV60W3FhuW](https://user-images.githubusercontent.com/2264908/148668036-d14d4dcf-0567-4b7c-b505-e1dd8a27ca89.png)

Check in fronted, if hex, then call hexToString and show the string result, or just show the raw data.

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/148727881-3c626537-cd58-4f89-828d-ca2c70827732.png)
